### ISSUE TITLE
null safe versions of logging and test packages fail the version solver.

### ISSUE THREAD

**Issue by wstrange** [dart-lang/logging#92]
I can't seem to find a pubspec combination that satisfies the solver for logging and test:

```
name: test_null
description: A sample command-line application.

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  logging: "^1.0.0-nullsafety"

dev_dependencies:
  test: ^1.16.0-nullsafety

```

**Comment by NebulaFox** [comment]
I found the same problem while working on a flutter app.

```
dependencies:
  logging: ^1.0.0-nullsafety

dev_dependencies:
  integration_test:
    sdk: flutter
```

Resulting in the error message:

```
[App] flutter pub get
Running "flutter pub get" in App...                           
Because every version of integration_test from sdk depends on logging 0.11.4 and App depends on logging ^1.0.0-nullsafety, integration_test from sdk is forbidden.

So, because App depends on integration_test any from sdk, version solving failed.
pub get failed (1; So, because App depends on integration_test any from sdk, version solving failed.)
exit code 1
```

The funny thing is, as far as I can see, `integration_test` does not depend on `logging`
